name: Package and release

on:
  push:
    tags:
      - '**'

jobs:

  release-libmythickeystone:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .git symlink for monorepo
        run: |
          git config core.worktree "$GITHUB_WORKSPACE"
          ln -s "$GITHUB_WORKSPACE/.git" LibMythicKeystone/.git
      - name: Package and release LibMythicKeystone
        uses: BigWigsMods/packager@v2
        with:
          args: -t LibMythicKeystone

  release-mythickeystone:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .git symlink for monorepo
        run: |
          git config core.worktree "$GITHUB_WORKSPACE"
          ln -s "$GITHUB_WORKSPACE/.git" MythicKeystone/.git
      - name: Package and release MythicKeystone
        uses: BigWigsMods/packager@v2
        with:
          args: -t MythicKeystone

  release-mythickeystone-libdatabroker:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .git symlink for monorepo
        run: |
          git config core.worktree "$GITHUB_WORKSPACE"
          ln -s "$GITHUB_WORKSPACE/.git" MythicKeystone_LibDataBroker/.git
      - name: Package and release MythicKeystone_LibDataBroker
        uses: BigWigsMods/packager@v2
        with:
          args: -t MythicKeystone_LibDataBroker
